### ISSUE TITLE
just want to say thank you very much

### ISSUE THREAD

**Issue by devmondo** [JustSid/AfterglowIntelliJ#1]
sorry to post this here as i dont know where else to say thank you very much for this theme, it is so beautiful and makes webstorm so much better to the eyes :)

**Comment by JustSid** [comment]
Thank you so much! :)

Sorry for leaving you hanging so long, for some reason the two issues on this project drowned out completely and I wasn't even aware of them. Also I'll immediately close this issue now, but, thank you so much for your kind words. Greatly appreciated.
