### ISSUE TITLE
Add .vue file icons

### ISSUE THREAD

**Issue by agileago** [JustSid/AfterglowIntelliJ#13]
![vue](https://cloud.githubusercontent.com/assets/11799110/14222788/9a68f728-f8a7-11e5-8eb1-46ac28b18567.png)
![vue 2x](https://cloud.githubusercontent.com/assets/11799110/14222789/9a6d8e1e-f8a7-11e5-8224-3f78afa6ea9f.png)

thanks

**Comment by JustSid** [comment]
This will be in 1.0.7. In the meantime until its release, you can build the plugin yourself :)
