### ISSUE TITLE
Unable to import the plugin in android studio

### ISSUE THREAD

**Issue by crazyhitty** [JustSid/AfterglowIntelliJ#14]
Hello,
I am getting some weird error while importing this plugin in android studio ver 1.5

[Screenshot](https://www.dropbox.com/s/8qjfb6v0k9a7or0/Screenshot%202016-04-08%2019.50.39.png?dl=0)

**Comment by JustSid** [comment]
The plugin requires Java version 8, so you'll have to update your Java runtime I'm afraid, which is what the error message is complaining about.
