### ISSUE TITLE
JS files often load with Gulp icon, restart needed to fix

### ISSUE THREAD

**Issue by mliq** [JustSid/AfterglowIntelliJ#16]
Frequently I open my project and all JS files have a Gulp icon. Closing and restart fixes this. Any idea what could cause? (Webstorm 2016.1.1, OSX 10.11.4) 

I am also using [https://github.com/ChrisRM/material-theme-jetbrains](https://github.com/ChrisRM/material-theme-jetbrains), perhaps a conflict there? (I have isolated the problem to AfterglowIntelliJ).

Thanks for the beautiful work!

**Comment by JustSid** [comment]
What version are you using? I thought I had fixed that issue with 1.0.7

**Comment by JustSid** [comment]
Never mind, this appears to be still an issue in 1.0.7... Damn, looks like I'll have to rethink my caching strategy. I'll try to get a fix out later today!

**Comment by JustSid** [comment]
I'm pretty sure this is fixed in 69b5877 , but just to be safe, can you give it a try? I've compiled you a version here to make it easier: http://cl.widerwille.com/fefh
