### ISSUE TITLE
Typescript icons, react

### ISSUE THREAD

**Issue by asvetliakov** [JustSid/AfterglowIntelliJ#17]
Typescript (ts extension)
![ts](https://raw.githubusercontent.com/ctf0/Seti_ST3/master/icons/file_type_typescript.png)
![ts2](https://raw.githubusercontent.com/ctf0/Seti_ST3/master/icons/file_type_typescript%402x.png)

React (jsx, tsx extensions)
![jsx](https://raw.githubusercontent.com/ctf0/Seti_ST3/master/icons/file_type_react.png)
![jsx2](https://raw.githubusercontent.com/ctf0/Seti_ST3/master/icons/file_type_react%402x.png)

Thanks

**Comment by JustSid** [comment]
Hey, sorry for the late reply. I'm currently working on a better theme engine that allows easily adding support for custom file icons. I was actually hoping I'd had it done by now, but alas real life got in the way as per the usual. Just wanted to let you know that I have seen the issue though :)

**Comment by JustSid** [comment]
This is finally added in 75d0810e3bfa8190409d303ba06ce55406d8758f. Sorry for taking ages to get to this.
