### ISSUE TITLE
Icons replaced in Database view

### ISSUE THREAD

**Issue by johan-miller** [JustSid/AfterglowIntelliJ#19]
Would it be possible to not override the icons on the Database view? Currently almost all of the icons are shown as folders. This would be ok for tables but for columns this means what vital information about the column is lost.

![image](https://cloud.githubusercontent.com/assets/3204050/14711483/c3989a40-07d9-11e6-9f8a-3b7985a8a3eb.png)

**Comment by JustSid** [comment]
Errr, that might be a stupid question, but can you tell me how to get to that view? I have never seen it, but I feel like it's not present in my main IDEs CLion and AppCode.

**Comment by johan-miller** [comment]
I am using IntelliJ IDEA Ultimate and I believe it is a part of the database tools which is offered. There is a tab on the right side of IDEA called Database. I believe it should be about the same as the separate [DataGrip ](https://www.jetbrains.com/datagrip) tool which they offer. The icons at least look the same like in the screenshots.

**Comment by JustSid** [comment]
The issue also existed in DataGrip as well, it's fixed in 5941744d92024ab2b0c6472ece61f3d745ee680b. Sorry for taking so long.

**Comment by johan-miller** [comment]
Great! Do you know when you will be releasing a new version with the fix?
