### ISSUE TITLE
Freezes Webstorm 11

### ISSUE THREAD

**Issue by atom0s** [JustSid/AfterglowIntelliJ#4]
Tried installing this on Webstorm 11 and it just freezes on startup. Removing the plugin's .jar file allows Webstorm to start as normal.

**Comment by JustSid** [comment]
It works fine for me in WebStorm 11.0.2 (Build 143.1184). What version are you using? Also, what operating system are you on?

**Comment by atom0s** [comment]
Webstorm 11.0.3
Build #WS-143.1559, built on December 23, 2015

**Comment by JustSid** [comment]
Interesting, I thought I was on the latest version. Anyway, I checked out WebStorm 11.0.3 and it runs flawlessly on Mac OS X 10.11. What operating system are you on?

**Comment by atom0s** [comment]
Windows 8.1 tested on two machines.  Both freeze on startup.

**Comment by JustSid** [comment]
Thanks! I'll see about getting my hands on some Windows 8.1 machine to track that down.

**Comment by atom0s** [comment]
If there is any other info I can get you to help you out let me know.

**Comment by JustSid** [comment]
Okay, well, I didn't get to test it on Windows 8.1 but I tested it on Windows 10 and it seems to work there. Dunno if that is Windows 10 though. On a second thought though, do you maybe have any other plugins installed? Maybe there is some issue there? I'll also see about installing Windows 8.1.

**Comment by atom0s** [comment]
When I attempted to use this, no. Just the default plugins that came with Webstorm only. I've since installed other things though. But not prior.

**Comment by JustSid** [comment]
Damn... Okay, I'll see about that Windows 8.1 install. Sorry for taking so long, I'm not really a Windows user and this is proving quite tricky for me actually.

**Comment by atom0s** [comment]
No worries, thanks for your time. :)

**Comment by JustSid** [comment]
This should _finally_ be fixed in 1.0.6
